docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - "Event Dispatcher": dispatcher.md
      - "Listener Providers": listener-providers.md
      - "Lazy Listeners": lazy-listeners.md
      - "Services": services.md
site_name: 'phly-event-dispatcher'
site_description: 'Component Description goes here'
repo_url: 'https://github.com/phly/event-dispatcher'
copyright: 'Copyright (c) <a href="https://mwop.net/">Matthew Weier O\'Phinney</a>'
