name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'
      - 'renovate/*'
    tags:

jobs:
  ci:
    uses: laminas/.github/.github/workflows/continuous-integration.yml@feature/ci-workflow-template
